### ISSUE TITLE
License is missing

### ISSUE THREAD

**Issue by ChrisOboe** [0x17de/dockerservice-openrc#1]
Hi,

i want to create an ebuild (a package for portage, the package manager used by gentoo) for this openrc init script. For a ebuild the license information is mandatory. 

Could you please add information about the license.

**Comment by 0x17de** [comment]
Hi @ChrisOboe, thanks i forgot :) oops. I assume the MIT license works well for you

**Comment by ChrisOboe** [comment]
yes, MIT is fine. Thank you!
